### PR TITLE
Move to neotraverse

### PR DESCRIPTION
**Pull request by danawoodman**
Drastically reduces bundle size (125k to 19k) and depedency graph reduced from dozes to about 6 deps

Tests still passing

Before:

image

After:

image

### CODE REVIEW

**Comment by danawoodman** [comment]
@SnailBones @mapsam i know this project is very old, but any chance yall could review/merge this PR?

**Comment by mapsam** [comment]
Hey there @danawoodman thanks for the ping! I'm no longer at Mapbox so don't have the ability to merge PRs any longer. 

Pinging @greenlaw @AlexanderBelokon for some additional eyes. 🙏

**Review by greenlaw — APPROVED** [review]
LGTM.  Thanks for the contribution.  I may follow up with a version bump.

**Comment by danawoodman** [comment]
thank you!

**Pull request merged**
